version: '3'
services:
        web:
                image: flask_port_v1
                build: .
                ports:
                        - "8186:8186"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                        - ./movies:/movies
                restart: unless-stopped