version: '3'
services:
  web:
    build: .
    ports:
      - "8086:8086"
    network_mode: "host"  # Add this line
    volumes:
      - persistent_volume:/volumes
    restart: unless-stopped

volumes:
  persistent_volume:
    driver: local